name: Terraform Init
description: Runs `terraform init` in the current working directory

inputs:
  WORKING_DIR:
    description: "Directory containing Terraform configuration"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Initialize Terraform
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}