name: Packer Validations

on:
  push:
    paths:
      - '**.pkr.hcl'
      - '.github/**'
  pull_request:
    paths:
      - '**.pkr.hcl'

  workflow_dispatch:
     inputs:
       working-directory:
         description: "Subdirectory where Packer files are located"
         required: true
         default: "./packer/artifactory-lxc-packer/lxc"


jobs:
  packer-check:
    name: Validate Packer Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: 🎨 Format Packer files
        run: |
          echo "Checking Packer formatting in: ${{ inputs.working-directory }}"
          packer fmt -check -diff "${{ github.workspace }}/${{ inputs.working-directory }}"
        shell: bash
      
      - name: Run Packer CI checks
        uses: ./.github/action/packer-init
        with:
          working-directory: ${{ inputs.working-directory }}

      