# name: Validate Terraform

# on:
#   push:
#     branches:
#       - 'main'  # Trigger only on push to the main branch
#     paths:
#       - 'terraform/**'  # Only triggers if there is a change in the ./terraform directory